window.STOCK_TABLE_DATA = {
  asOf: "2026-07-17",
  version: "v1.3",
  title: "中国AI产业链选股表",
  ruleNote: "覆盖A股/港股/中概。潜力 = 质量（利润池持续性 × 边际变化）× 定价未充分程度。持续性 = 紧缺度 × 扩产难度 × 定价权（相乘，任一≤3判不可持续）。与 Global Stocks 同一套框架，另加中国特有约束：国产替代进度=紧缺度的放大器；出口管制既是护城河也是天花板。质量分低频更新；估值列与依据列每周联网刷新。",
  scoreAnchors: [
    "紧缺度：9-10=国产化率<20%且订单排满（先进制程代工/EUV前道设备）；7-8=国产化率20-50%且交期>26周；5-6=偏紧但可获得；≤3=充分竞争现货可得",
    "扩产难度：9-10=受出口管制卡口或技术代差>3年（先进制程/EDA全流程/HBM）；7-8=2-3年（设备验证周期/先进封装）；5-6=1-2年（液冷/电源扩线）；≤3=<1年可扩（组装/PCB常规品）",
    "定价权：9-10=独家国产替代且在提价；7-8=双寡头价稳、成本可传导（光模块头部/接口芯片）；5-6=集中度高但大客户压价（服务器整机）；≤3=年度降价惯例（代工成熟制程/组装）",
    "估值双锚（按环节类型）：平台/软件=FPE vs 自身5年中枢；制造/设备=FPE + 在手订单能见度；周期品=毛利率历史分位 + P/B（禁用FPE排序，GM>80分位=顶部警戒）；未盈利科创板标的=PS + 研发管线里程碑，仓位额外减半"
  ],
  rows: [
    { rank: 1, segment: "半导体设备", vtype: "设备", scarcity: 9, pool: 8, expand: 9, pricing: 8, status: "✅", marginal: "🟢", leaders: "北方华创/中微/拓荆", fpe: "北方58.8 / 中微93（原口径）", anchor2: "能见度：北方在手订单超820亿（同比+58%）、覆盖2-2.5年、排产至2028；26Q1新签约195亿；中微26H1新签订单41亿(+40%)，条款2未触发", priced: "🟡", verdict: "逻辑最硬、估值不便宜", tier: "core", sizeBand: "6-10%",
      evidence: "26Q1北方华创营收103.2亿(+25.8%)、净利16.4亿(+3.4%)、新签订单约195亿、在手订单超820亿(+58%)；中微26H1新签订单41亿(+40%)、刻蚀+51%；7/3北方一度跌停属情绪、订单基本面未变" },
    { rank: 2, segment: "晶圆代工", vtype: "制造", scarcity: 9, pool: 7, expand: 9, pricing: 6, status: "✅", marginal: "🟢", leaders: "中芯 0981.HK / 华虹 1347.HK", fpe: "中芯H 66.2 / 华虹原口径", anchor2: "能见度：利用率93.1%远高于80%触发线；capex约81亿美元持平未下调", priced: "🟡", verdict: "瓶颈强化，优先H股", tier: "core", sizeBand: "6-10%",
      evidence: "中芯26Q1产能利用率93.1%（同比+3.5pct），月产能107.8万片；Q2指引收入环比+14~16%、毛利率20-22%明显上修；2026 capex约81亿美元持平；两地价差大" },
    { rank: 3, segment: "AI算力芯片", vtype: "制造", scarcity: 8, pool: 8, expand: 8, pricing: 7, status: "✅", marginal: "🟢", leaders: "寒武纪 / 海光信息", fpe: "寒武300+ / 海光266", anchor2: "PS：寒武2026E~30x+；出货未低于指引，条款3安全；出口管制收紧使英伟达中国份额降至~0，条款9反向强化国产替代（非放松）", priced: "🔴", verdict: "按条款3+9持有、不加仓", tier: "debate", sizeBand: "3-5%",
      evidence: "海光7/16中报预增：H1净利17-18.3亿(+41.5%~52.3%)、Q2环比+47%创单季新高、营收+55.6%~70.2%、扣非口径+74~84%，出货未低于指引；寒武纪26Q1营收28.85亿(+160%)已扭亏；英伟达对华份额~0，国产AI卡受益；寒武7月初跌破万亿市值并自主提示稀缺性溢价风险" },
    { rank: 4, segment: "光模块", vtype: "制造", scarcity: 7, pool: 8, expand: 6, pricing: 7, status: "✅", marginal: "🟢", leaders: "中际旭创/新易盛/天孚", fpe: "旭创34.2 / 新易盛22-24（原口径）", anchor2: "能见度：7/12旭创澄清『小作文』：1.6T需求未减仅客户结构调整、在手订单覆盖2026全年、部分客户已给2027季度指引，条款4未触发", priced: "🟢", verdict: "质量/估值比最优、新易盛更低", tier: "core", sizeBand: "6-10%",
      evidence: "7/12-13砍单传闻致市值一度蒸发千亿，公司澄清：1.6T需求强劲、800G需求超预期增加、订单覆盖全年+2027部分能见度；新易盛26Q1营收83.4亿(+106%)、净利27.8亿(+77%)；瓶颈在供给端非需求端，中报为验证节点" },
    { rank: 5, segment: "先进封装/封测", vtype: "制造", scarcity: 7, pool: 6, expand: 7, pricing: 6, status: "✅", marginal: "🟢", leaders: "长电科技 / 通富微电", fpe: "长电~45 / 通富(净利+80%)", anchor2: "能见度：长电PE(2026E)~45x、目标价49.2；通富先进封装放量", priced: "🟡", verdict: "利润率拐点初现", tier: "debate", sizeBand: "3-5%",
      evidence: "通富2025年收入279亿(+17%)、净利12.2亿(+80%)，HybridSiP/高叠层推进；长电为国内封测龙头" },
    { rank: 6, segment: "EDA/IP", vtype: "平台", scarcity: 8, pool: 5, expand: 9, pricing: 6, status: "⚠️", marginal: "🔴", leaders: "华大九天 / 芯原股份", fpe: "华大极高(业绩暴跌)", anchor2: "中枢：华大25年前三季净利-84.5%，估值严重透支；芯原未盈利按PS", priced: "🔴", verdict: "长逻辑短兑现、太贵", tier: "debate", sizeBand: "0-3%",
      evidence: "国产EDA全流程覆盖率仍低、替代空间大但兑现慢；华大九天业绩大幅下滑而股价高企，性价比差" },
    { rank: 7, segment: "存储/HBM链", vtype: "周期", scarcity: 7, pool: 6, expand: 8, pricing: 6, status: "⚠️", marginal: "🟡", leaders: "兆易创新 / 香农芯创", fpe: "—（周期品）", anchor2: "GM分位：兆易26Q1 GM 57.1%达历史高分位(25年全年40%)，DDR5 16Gb合约价一年+681%(4.8→37.5美元)、7月初现货3天再涨超1000元，周期顶部特征持续强化", priced: "🔴", verdict: "⚠周期顶部、止盈不加仓", tier: "debate", sizeBand: "0-3%",
      evidence: "兆易26Q1营收41.9亿(+119%)、净利14.6亿(+523%)、GM57.1%；双16G DDR5条7/6突破4000元、3天涨超1000元；机构预计价格回落最早2027；接近条款7触发（长鑫未上市）" },
    { rank: 8, segment: "接口/互连芯片", vtype: "制造", scarcity: 7, pool: 6, expand: 7, pricing: 8, status: "✅", marginal: "🟢", leaders: "澜起科技 / 聚辰股份", fpe: "澜起46-52 (PEG~1.1)", anchor2: "中枢：GM62%远高于55%触发线，条款5安全；DDR5+新品放量", priced: "🟡", verdict: "最高质量设计公司之一", tier: "core", sizeBand: "5-8%",
      evidence: "澜起2025年GM62.2%(+4.1pct)、净利+58%；26Q1营收14.6亿、净利8.5亿；内存接口全球双寡头之一" },
    { rank: 9, segment: "AI服务器/整机", vtype: "制造", scarcity: 5, pool: 6, expand: 4, pricing: 4, status: "✅", marginal: "🟡", leaders: "工业富联 / 浪潮信息", fpe: "工业富联33x (2026E)", anchor2: "毛利率：组装环节定价权弱、GM低，量的弹性≠利润弹性", priced: "🟡", verdict: "只做贝塔", tier: "watch", sizeBand: "3-5%",
      evidence: "工业富联为核心AI算力整机供应商、AI服务器需求能见度改善；给33x溢价 vs 同业均值22x" },
    { rank: 10, segment: "PCB/CCL", vtype: "制造", scarcity: 6, pool: 6, expand: 5, pricing: 6, status: "✅", marginal: "🟢", leaders: "沪电/生益/胜宏", fpe: "沪电32.3 / 生益93 / 胜宏65", anchor2: "能见度：沪电26年净利均值57亿(+49.6%)，AI服务器PCB核心供应商", priced: "🟡", verdict: "景气高、盯供给", tier: "debate", sizeBand: "3-5%",
      evidence: "高多层/HDI供需偏紧，AI服务器单机PCB价值量数倍提升；沪电PEG相对最优、生益/胜宏更贵" },
    { rank: 11, segment: "液冷/温控", vtype: "设备", scarcity: 6, pool: 5, expand: 5, pricing: 5, status: "✅", marginal: "🟢", leaders: "英维克", fpe: "英维克71.7（NTM，偏贵）", anchor2: "能见度：数据中心液冷订单随高功率密度机柜放量", priced: "🔴", verdict: "逻辑清晰、护城河一般", tier: "debate", sizeBand: "3-5%",
      evidence: "高功率密度机柜使液冷从可选变必选、渗透率提升；但技术壁垒有限、估值已偏高" },
    { rank: 12, segment: "数据中心电源", vtype: "设备", scarcity: 6, pool: 5, expand: 5, pricing: 5, status: "✅", marginal: "🟡", leaders: "麦格米特 / 欧陆通", fpe: "麦格米特91.5（NTM）", anchor2: "能见度：HVDC/高压直流随AI机柜功率抬升", priced: "🟡", verdict: "跟随环节、合理才碰", tier: "watch", sizeBand: "2-4%",
      evidence: "服务器大功率电源与HVDC受益AI机柜功率上行；跟随属性、非瓶颈核心" },
    { rank: 13, segment: "IDC/算力租赁", vtype: "制造", scarcity: 5, pool: 5, expand: 4, pricing: 4, status: "✅", marginal: "🟡", leaders: "润泽科技 / 万国数据 9698.HK", fpe: "润泽44.0；核心仍按上架率定价", anchor2: "上架率：智算中心供给放量快、同质化，上架率是唯一硬校验", priced: "🟡", verdict: "警惕产能过剩", tier: "watch", sizeBand: "2-4%",
      evidence: "智算中心供给快速放量、竞争同质化；重资产低门槛，条款8（上架率<50%）为清零线" },
    { rank: 14, segment: "半导体材料", vtype: "制造", scarcity: 7, pool: 4, expand: 7, pricing: 5, status: "✅", marginal: "🟢", leaders: "沪硅/安集/南大光电", fpe: "沪硅(净利CAGR~25%)", anchor2: "导入进度：光刻胶/大硅片国产化率低、替代确定但单环节利润池小", priced: "🟡", verdict: "逻辑硬、弹性小、配角", tier: "watch", sizeBand: "2-4%",
      evidence: "关键材料国产替代确定性高但单点利润池有限；组合配角，不宜重仓" },
    { rank: 15, segment: "云平台/大模型", vtype: "平台", scarcity: 6, pool: 9, expand: 8, pricing: 6, status: "✅", marginal: "🔴 NTM~36d -1.2%", leaders: "腾讯 0700.HK / 阿里 9988.HK", fpe: "腾讯13.3 / 阿里原口径", anchor2: "中枢：阿里云增速加速至38-40%、AI收入占外部云超30%，capex持续上调，条款6(增速<10%)远未触发", priced: "🟢", verdict: "基本面/估值背离最大", tier: "core", sizeBand: "6-10%",
      evidence: "阿里云四财季+38%、外部客户+40%、AI相关收入89.7亿(占外部云30%+)，capex指引或超3800亿；腾讯26Q1 capex 319亿(+16%)、下半年再增；『没有一张卡是空的』" }
  ],
  portfolioRules: [
    "总敞口：中国科技股合计不超过权益仓位的40%；单一环节≤15%，单票≤10%",
    "科创板未盈利标的仓位在档位基础上再减半；北向/外资流向连续4周流出时暂停加仓",
    "对冲：组合贝塔过高时用恒生科技指数期权或减仓对冲，不裸空个股",
    "A/H两地上市优先选折价一侧；中概退市风险标的只用可损失仓位",
    "触发纪律：任一可证伪条款触发，48小时内机械执行减仓，不辩经"
  ],
  tiers: [
    "core（核心）：半导体设备 / 晶圆代工 / 光模块 / 接口芯片 / 云平台——瓶颈地位或全球定价权明确",
    "debate（观察辩论）：AI芯片 / 先进封装 / EDA / 存储 / PCB / 液冷——逻辑成立但估值或兑现存分歧",
    "watch（跟踪）：服务器整机 / 电源 / IDC / 材料——跟随环节，只在明显低估时参与"
  ],
  falsifiers: [
    "1. 中芯国际先进制程产能利用率跌破80%或资本开支指引下调>20% → 代工与设备链减半",
    "2. 北方华创/中微在手订单同比增速转负 → 设备环节清零重估",
    "3. 寒武纪/海光出货量连续两季低于指引 → AI芯片仓位清零",
    "4. 中际旭创1.6T订单指引下修或海外大客户砍单 → 光模块减半",
    "5. 澜起科技毛利率跌破55% → 接口芯片减半",
    "6. 腾讯/阿里云业务增速连续两季<10%且capex继续上行 → 云平台减半",
    "7. 存储毛利率升至历史80分位以上 → 存储链条止盈（周期顶部纪律）",
    "8. 智算中心上架率行业均值<50%的证据出现 → IDC清零",
    "9. 出口管制出现实质性放松（英伟达高端卡恢复对华销售）→ 全表国产替代逻辑重估",
    "10. 恒生科技/科创50跌破年线且北向连续8周流出 → 总敞口压至20%以下"
  ],
  dataNote: "v1.3（2026-07-17周更）：StockAnalysis本周返回缓存全部旧于7/13已入库观测（缓存回退现象），估值列保留7/13口径不回退，EPS序列全票记unchanged。腾讯首次获得跨度≥30天的NTM修正读数：6/7→7/13（36天）NTM EPS 34.89→34.46（-1.2%，HKD口径，可能含汇率与缓存噪音），机械写入边际列。新增硬数据：北方在手订单超820亿(+58%)、海光中报预增+41.5~52.3%、旭创7/12澄清1.6T未砍单。10条可证伪条款均未触发；质量分、tier、仓位不变。",
  disclaimer: "仅为个人研究参考，非投资建议。"
};
